name: Remove a label
on:
  project_card:
    types:
      - moved
jobs:
  remove_label:
    - uses: actions/checkout@v3

    # Make changes to pull request here

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5